## USB port
port: /dev/razor-imu-9dof


##### Calibration ####
### accelerometer
accel_x_min: -254.39
accel_x_max: 253.17
accel_y_min: -251.95
accel_y_max: 256.84
accel_z_min: -258.18
accel_z_max: 255.25

### magnetometer
# standard calibration
magn_x_min: -444.11
magn_x_max: 231.06
magn_y_min: -457.16
magn_y_max: 460.62
magn_z_min: -198.05
magn_z_max: 417.10

# extended calibration
calibration_magn_use_extended: false
magn_ellipsoid_center: [5.67173, 30.7189, -45.5617]
magn_ellipsoid_transform: [[0.862679, 0.0463829, 0.140119], [0.0463829, 0.918278, -0.115381], [0.140119, -0.115381, 0.786916]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: 0.02
gyro_average_offset_y: -0.03
gyro_average_offset_z: 0.01
