#No. 1
## USB port
port: /dev/ttyACM1


##### Calibration ####
### accelerometer
accel_x_min: -261.35
accel_x_max: 248.17
accel_y_min: -250.49
accel_y_max: 255.86
accel_z_min: -276.98
accel_z_max: 253.17

### magnetometer
# standard calibration
magn_x_min: 79.52
magn_x_max: 909.23
magn_y_min: -210.05
magn_y_max: 588.15
magn_z_min: -577.64
magn_z_max: 243.06

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [472.779, 180.198, -196.701]
magn_ellipsoid_transform: [[0.993871, 0.00773798, 0.00445768], [0.00773798, 0.987027, 0.00269223], [0.00445768, 0.00269223, 0.975142]]
# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: -0.01
gyro_average_offset_y: 0.01
gyro_average_offset_z: 0.02
